DROP TABLE IF EXISTS PACIENTES; CREATE TABLE PACIENTES(ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL,
DNI VARCHAR(100) NOT NULL, FECHAINGRESO VARCHAR(100) NOT NULL)

DROP TABLE IF EXISTS DOMICILIO; CREATE TABLE DOMICILIO(ID INT AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(100) NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(100) NOT NULL, PROVINCIA VARCHAR(100) NOT NULL, ID_PACIENTE INT UNIQUE, FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID))